name: image_gallery
description: "this is an image gallery app which is an assignment task from Cheq Lifestyle 
Technology Inc."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.0
  flutter_bloc: ^8.1.6
  flutter_splash_screen: ^3.0.0
  flutter_svg: ^2.0.16
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
          style: normal

    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
          style: normal


